/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.crio.qcalc;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        StandardCalculator calc = new StandardCalculator();
        //calc.add(1,2);
        //System.out.println(calc.getResult());

        //now priting the overflow values conditions
        calc.add(2.3,4.5);
        //calc.add(Double.MAX_VALUE, Double.MAX_VALUE);
        calc.printResult();
        //System.out.println(new App().getGreeting());

        

        //for logic calculator class functioninng
        LogicCalculator calc2 = new LogicCalculator();
        calc2.OR(8, 6);
        calc2.printResult();

    }
}
